export interface ProductCategoryRecord {
  id: string;
  code: string;
  name: string;
  description: string;
}

const baseNames = [
  'Electronics',
  'Clothing',
  'Home & Kitchen',
  'Books',
  'Sports & Outdoors',
  'Beauty & Personal Care',
  'Toys & Games',
  'Automotive',
  'Health & Wellness',
  'Pet Supplies',
];

/**
 * Temporary, in-memory mock dataset. 50 categories generated by cycling the
 * base names so there is enough data to paginate. Not a production source.
 */
export const productCategoryTempData: ProductCategoryRecord[] = Array.from(
  { length: 50 },
  (_, index) => {
    const number = index + 1;
    const baseName = baseNames[index % baseNames.length];
    return {
      id: `product-category-${number}`,
      code: `PC-${String(number).padStart(3, '0')}`,
      name: `${baseName} ${Math.floor(index / baseNames.length) + 1}`,
      description: `Category for ${baseName.toLowerCase()} products (#${number})`,
    };
  }
);
