import './global.css';

export const metadata = {
  title: 'Welcome to @r10c/marketplace-admin-app',
  description: 'Generated by create-nx-workspace',
};

import { Providers } from './providers';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="aurora" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
