import {
  type Permission,
  permissionForEntity,
  screenAddress,
} from '@r10c/business-ts-authz';
import { ProductSpecification } from '@r10c/business-ts-product-configuration-management';
import type { Entity, EntityConstructor } from '@r10c/entifix-ts-core';

/**
 * One guided screen, declared once for everything that has to name it.
 *
 * The sibling of `CatalogSurface`, and separate from it for the reason
 * [ADR 0033](../../../../../docs/adr/0033-the-screen-taxonomy.md) keeps the two
 * screen types apart: a catalog surface is generated by `makeEntityCrud`, and a
 * wizard is hand-built by design — Fiori reached the same split, every floorplan
 * generated except the wizard and the initial page. What they share is that the
 * nav item, the workspace address and the permission all **derive** from one
 * declaration rather than being written out per consumer.
 *
 * `entityConstructor` is the entity the flow **writes**, and it is here for one
 * job: the permission. A wizard that creates a `ProductSpecification` is guarded
 * by `product-configuration-management:product-specification:write`, derived
 * from the entity's own `@entity({ domain, key })` — a hand-written domain
 * string here could name a domain the route behind it does not check.
 */
export interface WizardSurface<TEntity extends Entity = Entity> {
  /** The flow's own screen key, and the second segment of its address. */
  readonly key: string;
  /** The entity the flow creates; supplies the permission that guards it. */
  readonly entityConstructor: EntityConstructor<TEntity>;
  readonly basePath: string;
  readonly icon: string;
  /** Shell-namespaced nav copy. `app:` keys are lint-restricted to `apps/`. */
  readonly navLabelKey: string;
  /** Gate the nav item on the organization's provisioning (ADR 0007). */
  readonly entitled?: boolean;
}

/** The `write` permission guarding a flow, derived from the entity it creates. */
export const permissionForWizard = (surface: WizardSurface): Permission =>
  permissionForEntity(surface.entityConstructor, 'write');

/**
 * A flow's workspace address.
 *
 * Only the flow's own address is built here. A step's address —
 * `wizard:<key>:<step>`, the third segment holding a step where `master:` holds
 * a record ([ADR 0045](../../../../../docs/adr/0045-the-wizard-a-step-graph-and-a-submit-that-hands-off.md))
 * — is `wizardTabKind`'s `toParam`, and a second builder for it here would be a
 * second spelling of one grammar, which is the drift `screenAddress` exists to
 * stop.
 */
export const wizardAddress = (surface: WizardSurface): string =>
  screenAddress({ type: 'wizard', key: surface.key });

/**
 * The guided alta of a product specification.
 *
 * It writes the one entity the fleet tracks transactionally
 * (`create: 'command'`), which is what lets its ending exercise the hand-off
 * ADR 0045 is shaped around rather than only describing it.
 */
export const PRODUCT_SETUP_SURFACE: WizardSurface<ProductSpecification> = {
  key: 'product-setup',
  entityConstructor: ProductSpecification,
  basePath: '/wizards/product-setup',
  icon: '◍',
  navLabelKey: 'shell:marketplaceAdmin.wizard.productSetup.title',
  // The same provisioning gate the products catalog carries: the flow authors a
  // record in the one domain an organization is actually entitled to.
  entitled: true,
};

/** Every guided screen this shell contributes, in the order they appear. */
export const MARKETPLACE_ADMIN_WIZARD_SURFACES: readonly WizardSurface[] = [
  PRODUCT_SETUP_SURFACE,
];
