apiVersion: v1
kind: Service
metadata:
  name: zitadel
spec:
  selector:
    app: zitadel
  ports:
    # Zitadel serves HTTP + gRPC (h2c) on 8080.
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
