export interface ProductBrandRecord {
  id: string;
  name: string;
  description: string;
  website: string;
}

const baseBrands = [
  'Acme',
  'Globex',
  'Umbrella',
  'Initech',
  'Soylent',
  'Hooli',
  'Stark',
  'Wayne',
  'Wonka',
  'Cyberdyne',
];

/**
 * Temporary, in-memory mock dataset. 20 brands generated by cycling the base
 * names so links can reference a stable pool of ids. Not a production source.
 */
export const productBrandTempData: ProductBrandRecord[] = Array.from(
  { length: 20 },
  (_, index) => {
    const number = index + 1;
    const baseName = baseBrands[index % baseBrands.length];
    const slug = baseName.toLowerCase();
    return {
      id: `product-brand-${number}`,
      name: `${baseName} ${Math.floor(index / baseBrands.length) + 1}`,
      description: `Products manufactured by ${baseName} (#${number})`,
      website: `https://www.${slug}.example.com`,
    };
  }
);
