export interface ProductBrandRecord {
  id: string;
  name: string;
  description: string;
  website: string;
  status: 'active' | 'retired';
}

const baseBrands = [
  'Acme',
  'Globex',
  'Umbrella',
  'Initech',
  'Soylent',
  'Hooli',
  'Stark',
  'Wayne',
  'Wonka',
  'Cyberdyne',
];

/**
 * Temporary, in-memory mock dataset. 20 brands generated by cycling the base
 * names so links can reference a stable pool of ids. Not a production source.
 *
 * Every fourth row seeds **retired**, so the retire verb has something to fail
 * on out of the box: selecting a mixed range and running it is what shows the
 * per-row report doing its job, and a fleet where every row succeeds
 * demonstrates nothing about partial failure. Changing this needs a
 * `dev:reset` — the seed only writes into an empty collection.
 */
export const productBrandTempData: ProductBrandRecord[] = Array.from(
  { length: 20 },
  (_, index) => {
    const number = index + 1;
    const baseName = baseBrands[index % baseBrands.length];
    const slug = baseName.toLowerCase();
    return {
      id: `product-brand-${number}`,
      name: `${baseName} ${Math.floor(index / baseBrands.length) + 1}`,
      description: `Products manufactured by ${baseName} (#${number})`,
      website: `https://www.${slug}.example.com`,
      status: number % 4 === 0 ? ('retired' as const) : ('active' as const),
    };
  },
);
